### ISSUE TITLE
When will release the source code of HEBO?

### ISSUE THREAD

**Issue by machanic** [huawei-noah/noah-research#5]
When will  publicly release the source code of HEBO? which is sota black-box optimization

**Comment by Alaya-in-Matrix** [comment]
Hello, the code is being reviewed internally to ensure that it complies with our open source standards and is free of legal issues. We will do our best to speed up the review process.

**Comment by Alaya-in-Matrix** [comment]
@machanic Hi, the code has been released in https://github.com/huawei-noah/noah-research/tree/master/HEBO

**Comment by machanic** [comment]
@Alaya-in-Matrix Can I use this code in the high dimensional variable optimization problem? Like black-box attack adversarial attack which optimizes the high-dimensional pixels as the variables.

**Comment by alexanderimanicowenrivers** [comment]
@machanic No problem, you can definitely try!

**Comment by machanic** [comment]
@alexanderimanicowenrivers HEBO is based on BO, However, BO does not support high-dimensional variable optimization. Does HEBO supports it?

**Comment by haithamb** [comment]
@machanic you are right. HEBO is created to support hyper-parameter tuning of machine learning models. It should be able to work on acceptable sizes of hyper-param dimensions. Beyond that you might need other forms of GPs and BO -- e.g., variational due to the increased data you'd need to handle high-d or you might want to do latent space BO algorithms that build a latent model first and then do BO in the latent space. If you opt for Latent space BO, HEBO can still be used in the latent space for searching. In fact, we have some work coming-up on latent space BO so stayed tuned!
