### ISSUE TITLE
[CLIFF] What focal length is used for AGORA evaluation experiment?

### ISSUE THREAD

**Issue by pixelite1201** [huawei-noah/noah-research#95]
Hello,
Thanks for the great work! 
Regarding the AGORA evaluation experiment, did you use assumed focal length or ground truth focal length from the training data?

**Comment by zhihaolee** [comment]
For the AGORA evaluation experiment, we use the assumed focal length: f_CLIFF = (img_w + img_h) / 2.
But for finetuning on the AGORA training data, we use the ground truth.

**Comment by pixelite1201** [comment]
Oh! So despite using the assumed focal length instead of the ground truth focal length, the method is able to get lowest error on AGORA leaderboard?

**Comment by zhihaolee** [comment]
Yes, it is. And I think we can't get the ground truth focal length of the AGORA evaluation data, can we?



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 3, 2022 18:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [huawei-noah/noah-research] [CLIFF] What focal length is used forAGORA evaluation experiment? (Issue #95)




 
Oh! So despite using the assumed focal length instead of the ground truth focal length, the method is able to get lowest error on AGORA leaderboard?

**Comment by pixelite1201** [comment]
I just assumed that you tried to learn the focal length somehow. But it is interesting that despite huge difference in the ground truth and assumed focal length, the error still goes quite low. Thanks for your answer.

**Comment by pixelite1201** [comment]
Hello again,

Could you also share the checkpoint with AGORA finetuning?

**Comment by zhihaolee** [comment]
It's been uploaded here [[Google Drive](
    https://drive.google.com/drive/folders/1EmSZwaDULhT9m1VvH7YOpCXwBWgYrgwP?usp=sharing)]  as `hr48-PA53.7_MJE91.4_MVE110.0_agora_val.pt`.

**Comment by pixelite1201** [comment]
Thanks a lot.
